batch_size: '64'
buffer_freq: '20'
buffer_size: '200000'
env: Safexp-PointGoal1-v0
eval: 'False'
eval_episodes: '5'
exp_name: Safexp-PointGoal1-v0-para1
load_episode: '7000'
log_path: log
model_path: model
model_save_freq: '1000'
num_episode: '10000'
policy_freq_high: '2'
policy_freq_low: '2'
print_freq: '250'
render: 'False'
reward_scaling: '0.1'
save_video: 'False'
sleep: '-1'
start_training_steps: '2500'
steps_per_epoch: '30000'
subgoal_dim: '15'
td3: 'False'
train: 'True'
train_freq: '20'
writer_freq: '25'
