batch_size: '100'
buffer_freq: '10'
buffer_size: '200000'
env: Safexp-PointGoal0-v0
eval: 'False'
eval_episodes: '5'
exp_name: Safexp-PointGoal0-v0-para0
load_episode: '-1'
log_path: log
model_path: model
model_save_freq: '100'
num_episode: '500'
policy_freq_high: '2'
policy_freq_low: '2'
print_freq: '250'
render: 'False'
reward_scaling: '0.1'
save_video: 'False'
sleep: '-1'
start_training_steps: '2500'
steps_per_epoch: '30000'
subgoal_dim: '15'
td3: 'False'
train: 'True'
train_freq: '10'
writer_freq: '25'
